version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:80:80
    links:
      - wordpress:wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:fpm
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    links:
      - db:db
    networks:
      - wordpress-network

  db:
    image: mysql:latest 
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wordpress-network

networks:
  wordpress-network:
      driver: bridge
