version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:80:80
    links:
      - wordpress:wordpress
      - smtp:smtp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./wp-app:/var/www/html
    networks:
      - wordpress-network

  wordpress:
    build:
      context: wordpress-build
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./wp-app:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
    environment:
      WORDPRESS_WP_URL: http://localhost
      WORDPRESS_WP_TITLE: "A New AddPeople Build"
      WORDPRESS_WP_USER: admin
      WORDPRESS_WP_PASS: pass
      WORDPRESS_WP_MAIL: webadmin@addpeople.co.uk
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: MrDicksWHY
    links:
      - db:db
      - smtp:smtp
    networks:
      - wordpress-network

  db:
    image: mysql:latest 
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: MrDicksWHY
    networks:
      - wordpress-network

  smtp:
    image: namshi/smtp
    restart: always
    # environment:
    #   - POSTFIX_myhostname=mail.ben-plant.co.uk
    ports:
      - 127.0.0.1:25:25
    networks:
      - wordpress-network

networks:
  wordpress-network:
      driver: bridge
